# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'transactId-library-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for transactId-library-ios
  pod 'SwiftyJSON'
  pod 'Alamofire'

end

target 'transactId_library_ios-tests' do
  use_frameworks!

end

target 'transactId-demo-app' do
  use_frameworks!

end



